"""Mock Strava-style route discovery for Bengaluru & Delhi."""
from typing import Dict, List


DISCOVERY: Dict[str, List[Dict]] = {
    "bengaluru": [
        {
            "id": "blr-cubbon-loop",
            "name": "Cubbon Park Sunrise Loop",
            "city": "Bengaluru",
            "distance_km": 5.2,
            "difficulty": "easy",
            "elevation_gain_m": 42,
            "start": {"lon": 77.5946, "lat": 12.9762, "name": "Cubbon Park Gate 4"},
            "vibe": "Green canopy, well-lit paths, joggers' community.",
            "tags": ["well-lit", "flat", "shaded", "5:30am friendly"],
            "athletes_this_week": 1284,
        },
        {
            "id": "blr-ulsoor-lake",
            "name": "Ulsoor Lake Perimeter",
            "city": "Bengaluru",
            "distance_km": 3.8,
            "difficulty": "easy",
            "elevation_gain_m": 18,
            "start": {"lon": 77.6215, "lat": 12.9791, "name": "Ulsoor Lake Boat Club"},
            "vibe": "Waterfront breeze, temple bells at dawn.",
            "tags": ["waterfront", "flat", "photogenic"],
            "athletes_this_week": 642,
        },
        {
            "id": "blr-lalbagh-hills",
            "name": "Lalbagh Rock & Ridge",
            "city": "Bengaluru",
            "distance_km": 6.4,
            "difficulty": "moderate",
            "elevation_gain_m": 96,
            "start": {"lon": 77.5848, "lat": 12.9507, "name": "Lalbagh West Gate"},
            "vibe": "Rocky outcrop climb, birdsong, sunrise view from the peak.",
            "tags": ["hills", "scenic", "birds"],
            "athletes_this_week": 918,
        },
        {
            "id": "blr-koramangala-tempo",
            "name": "Koramangala Tempo 8K",
            "city": "Bengaluru",
            "distance_km": 8.1,
            "difficulty": "moderate",
            "elevation_gain_m": 74,
            "start": {"lon": 77.6245, "lat": 12.9352, "name": "Koramangala 5th Block"},
            "vibe": "Wide roads, coffee shops opening, urban energy.",
            "tags": ["urban", "cafes", "coach-recommended"],
            "athletes_this_week": 421,
        },
    ],
    "delhi": [
        {
            "id": "del-lodhi-gardens",
            "name": "Lodhi Gardens Heritage Loop",
            "city": "Delhi",
            "distance_km": 4.6,
            "difficulty": "easy",
            "elevation_gain_m": 22,
            "start": {"lon": 77.2197, "lat": 28.5931, "name": "Lodhi Gardens Gate 2"},
            "vibe": "Mughal ruins, ancient trees, dawn light through arches.",
            "tags": ["heritage", "flat", "photogenic", "well-lit"],
            "athletes_this_week": 1710,
        },
        {
            "id": "del-nehru-park",
            "name": "Nehru Park Circuit",
            "city": "Delhi",
            "distance_km": 3.1,
            "difficulty": "easy",
            "elevation_gain_m": 12,
            "start": {"lon": 77.1885, "lat": 28.5936, "name": "Nehru Park Main Gate"},
            "vibe": "Diplomatic quiet, sprinklers on grass, safe pre-dawn.",
            "tags": ["safe", "flat", "5:30am friendly"],
            "athletes_this_week": 588,
        },
        {
            "id": "del-yamuna-riverfront",
            "name": "Yamuna Riverfront Long",
            "city": "Delhi",
            "distance_km": 10.2,
            "difficulty": "hard",
            "elevation_gain_m": 68,
            "start": {"lon": 77.2500, "lat": 28.6100, "name": "Yamuna Ghat"},
            "vibe": "Wide open, wind off the river, fewer runners.",
            "tags": ["long", "riverfront", "solo"],
            "athletes_this_week": 202,
        },
        {
            "id": "del-india-gate",
            "name": "India Gate Rajpath Line",
            "city": "Delhi",
            "distance_km": 5.5,
            "difficulty": "easy",
            "elevation_gain_m": 8,
            "start": {"lon": 77.2295, "lat": 28.6129, "name": "India Gate Circle"},
            "vibe": "Ceremonial boulevard, cyclist crowd, sunrise silhouettes.",
            "tags": ["iconic", "flat", "photogenic"],
            "athletes_this_week": 2450,
        },
    ],
}


def list_discovery(city: str) -> List[Dict]:
    return DISCOVERY.get(city.lower(), [])
